// Package git provides worktree management, DoD checks, and push/PR helpers.
package git

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// SetupWorktree creates an isolated git worktree for a task.
// Handles stale branches/worktrees from previous failed runs.
// Returns the absolute path to the worktree directory.
func SetupWorktree(ctx context.Context, baseDir, taskID string) (string, error) {
	branch := fmt.Sprintf("chum/%s", taskID)
	wtDir := filepath.Join(os.TempDir(), "chum-worktrees", taskID)

	if err := os.MkdirAll(filepath.Dir(wtDir), 0o755); err != nil {
		return "", fmt.Errorf("mkdir worktree parent: %w", err)
	}

	// Clean up stale worktree if it exists from a previous failed run
	if _, err := os.Stat(wtDir); err == nil {
		cmd := exec.CommandContext(ctx, "git", "worktree", "remove", "--force", wtDir)
		cmd.Dir = baseDir
		_ = cmd.Run() // best-effort
		os.RemoveAll(wtDir)
	}

	// Delete stale branch if it exists (leftover from previous run)
	cmd := exec.CommandContext(ctx, "git", "branch", "-D", branch)
	cmd.Dir = baseDir
	_ = cmd.Run() // ignore error if branch doesn't exist

	// Prune any stale worktree entries
	cmd = exec.CommandContext(ctx, "git", "worktree", "prune")
	cmd.Dir = baseDir
	_ = cmd.Run()

	// Create the worktree on a new branch.
	// Use -c core.hooksPath=/dev/null to bypass any project hooks (e.g. beads)
	// that may reference tools not installed in the execution environment.
	cmd = exec.CommandContext(ctx, "git", "-c", "core.hooksPath=/dev/null",
		"worktree", "add", "-b", branch, wtDir, "HEAD")
	cmd.Dir = baseDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("git worktree add: %s: %w", string(out), err)
	}

	// Configure the worktree: set author and disable hooks so the agent
	// CLI doesn't trigger beads/bd hooks during its own git operations.
	for _, kv := range [][2]string{
		{"user.name", "CHUM v2"},
		{"user.email", "chum@localhost"},
		{"core.hooksPath", "/dev/null"},
	} {
		cmd = exec.CommandContext(ctx, "git", "config", kv[0], kv[1])
		cmd.Dir = wtDir
		_ = cmd.Run() // best-effort
	}

	return wtDir, nil
}

// ErrOnProtectedBranch is returned when an operation is attempted on master/main.
var ErrOnProtectedBranch = errors.New("on protected branch")

// AssertFeatureBranch returns an error if workDir is on master or main.
// All agent operations must happen on feature branches in isolated worktrees.
func AssertFeatureBranch(ctx context.Context, workDir string) error {
	cmd := exec.CommandContext(ctx, "git", "rev-parse", "--abbrev-ref", "HEAD")
	cmd.Dir = workDir
	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("cannot determine branch: %w", err)
	}
	branch := strings.TrimSpace(string(out))
	if branch == "master" || branch == "main" {
		return fmt.Errorf("%w: refusing to operate on %s — agents must work on feature branches", ErrOnProtectedBranch, branch)
	}
	return nil
}

// CleanupWorktree removes a git worktree.
func CleanupWorktree(ctx context.Context, baseDir, wtDir string) error {
	cmd := exec.CommandContext(ctx, "git", "worktree", "remove", "--force", wtDir)
	cmd.Dir = baseDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("git worktree remove: %s: %w", string(out), err)
	}
	return nil
}

// Push pushes the current branch to origin.
func Push(ctx context.Context, workDir string) error {
	cmd := exec.CommandContext(ctx, "git", "push", "-u", "origin", "HEAD")
	cmd.Dir = workDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("git push: %s: %w", string(out), err)
	}
	return nil
}

// CommitAll stages all changes and creates a commit.
// Returns true if a commit was created, false if nothing to commit.
func CommitAll(ctx context.Context, workDir, message string) (bool, error) {
	// Stage everything
	cmd := exec.CommandContext(ctx, "git", "add", "-A")
	cmd.Dir = workDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return false, fmt.Errorf("git add: %s: %w", string(out), err)
	}

	// Check if there's anything staged
	cmd = exec.CommandContext(ctx, "git", "diff", "--cached", "--quiet")
	cmd.Dir = workDir
	if err := cmd.Run(); err == nil {
		return false, nil // nothing to commit
	}

	// Commit
	cmd = exec.CommandContext(ctx, "git", "commit", "-m", message)
	cmd.Dir = workDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return false, fmt.Errorf("git commit: %s: %w", string(out), err)
	}
	return true, nil
}

// CreatePR creates a pull request using gh CLI.
// Falls back to logging the branch name if gh is not installed.
func CreatePR(ctx context.Context, workDir, title string) error {
	// Preflight: check gh exists
	if _, err := exec.LookPath("gh"); err != nil {
		return fmt.Errorf("gh CLI not installed — push succeeded but PR must be created manually")
	}

	cmd := exec.CommandContext(ctx, "gh", "pr", "create",
		"--title", title,
		"--body", "Auto-generated by CHUM v2",
	)
	cmd.Dir = workDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("gh pr create: %s: %w", string(out), err)
	}
	return nil
}

// CheckResult is the outcome of a single DoD check command.
type CheckResult struct {
	Command  string `json:"command"`
	Passed   bool   `json:"passed"`
	ExitCode int    `json:"exit_code"`
	Output   string `json:"output"`
}

// DoDResult is the aggregate outcome of all DoD checks.
type DoDResult struct {
	Passed   bool          `json:"passed"`
	Checks   []CheckResult `json:"checks"`
	Failures []string      `json:"failures"`
}

// PRInfo captures pull request metadata from gh.
type PRInfo struct {
	Number     int    `json:"number"`
	HeadRefOID string `json:"headRefOid"`
	URL        string `json:"url"`
}

// RunDoDChecks validates worktree integrity, checks for actual changes,
// then executes each check command. Returns the aggregate result.
func RunDoDChecks(ctx context.Context, workDir string, checks []string) DoDResult {
	result := DoDResult{Passed: true}

	// --- Preflight 1: worktree integrity ---
	if _, err := os.Stat(filepath.Join(workDir, ".git")); err != nil {
		return DoDResult{
			Passed: false,
			Failures: []string{fmt.Sprintf(
				"WORKTREE BROKEN: .git missing in %s — worktree was likely cleaned while workflow was running",
				workDir)},
		}
	}

	// --- Preflight 2: non-empty diff ---
	hasChanges, err := HasChanges(ctx, workDir)
	if err != nil {
		// Non-fatal — proceed to checks anyway
	} else if !hasChanges {
		return DoDResult{
			Passed:   false,
			Failures: []string{"NO CHANGES: agent produced no code changes — diff is empty"},
		}
	}

	// --- Preflight 3: npm check ---
	for _, check := range checks {
		if strings.Contains(check, "npm ") {
			if _, err := os.Stat(filepath.Join(workDir, "package.json")); err != nil {
				return DoDResult{
					Passed: false,
					Failures: []string{fmt.Sprintf(
						"WORKTREE BROKEN: package.json missing in %s (required for: %s)",
						workDir, check)},
				}
			}
			break
		}
	}

	// --- Run configured checks ---
	for _, check := range checks {
		cr := runCheck(ctx, workDir, check)
		result.Checks = append(result.Checks, cr)
		if !cr.Passed {
			result.Passed = false
			result.Failures = append(result.Failures,
				fmt.Sprintf("%s (exit %d)", check, cr.ExitCode))
		}
	}
	return result
}

// HasChanges returns true if the worktree has any diff vs its merge base.
// Checks both committed and uncommitted changes.
func HasChanges(ctx context.Context, workDir string) (bool, error) {
	// Check for uncommitted changes first
	cmd := exec.CommandContext(ctx, "git", "status", "--porcelain")
	cmd.Dir = workDir
	out, err := cmd.Output()
	if err != nil {
		return false, fmt.Errorf("git status: %w", err)
	}
	if len(strings.TrimSpace(string(out))) > 0 {
		return true, nil // uncommitted changes exist
	}

	// Check for committed changes vs origin/HEAD or main
	for _, base := range []string{"main", "master", "HEAD~1"} {
		cmd = exec.CommandContext(ctx, "git", "diff", "--stat", base)
		cmd.Dir = workDir
		out, err = cmd.Output()
		if err != nil {
			if errors.Is(err, context.Canceled) {
				return false, err
			}
			continue // try next base
		}
		if len(strings.TrimSpace(string(out))) > 0 {
			return true, nil
		}
	}

	return false, nil
}

func runCheck(ctx context.Context, workDir, command string) CheckResult {
	parts := strings.Fields(command)
	if len(parts) == 0 {
		return CheckResult{Command: command, Passed: true}
	}
	cmd := exec.CommandContext(ctx, parts[0], parts[1:]...)
	cmd.Dir = workDir
	out, err := cmd.CombinedOutput()
	cr := CheckResult{
		Command: command,
		Output:  string(out),
	}
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			cr.ExitCode = exitErr.ExitCode()
		} else {
			cr.ExitCode = 1
		}
		cr.Passed = false
	} else {
		cr.Passed = true
	}
	return cr
}

// GetPRInfo returns PR number/head SHA/url for the current branch or a specific PR.
func GetPRInfo(ctx context.Context, workDir string, prNumber int) (*PRInfo, error) {
	if _, err := exec.LookPath("gh"); err != nil {
		return nil, fmt.Errorf("gh CLI not installed")
	}

	args := []string{"pr", "view", "--json", "number,headRefOid,url"}
	if prNumber > 0 {
		args = []string{"pr", "view", fmt.Sprintf("%d", prNumber), "--json", "number,headRefOid,url"}
	}
	cmd := exec.CommandContext(ctx, "gh", args...)
	cmd.Dir = workDir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("gh pr view: %s: %w", string(out), err)
	}

	var info PRInfo
	if err := json.Unmarshal(out, &info); err != nil {
		return nil, fmt.Errorf("parse gh pr view JSON: %w", err)
	}
	if info.Number == 0 {
		return nil, fmt.Errorf("gh pr view returned empty PR number")
	}
	return &info, nil
}

// CreatePRInfo creates a PR and then returns PR metadata for the current branch.
func CreatePRInfo(ctx context.Context, workDir, title string) (*PRInfo, error) {
	if err := CreatePR(ctx, workDir, title); err != nil {
		return nil, err
	}
	return GetPRInfo(ctx, workDir, 0)
}
