// Package git provides worktree management, DoD checks, and push/PR helpers.
package git

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// SetupWorktree creates an isolated git worktree for a task.
// Returns the absolute path to the worktree directory.
func SetupWorktree(ctx context.Context, baseDir, taskID string) (string, error) {
	branch := fmt.Sprintf("chum/%s", taskID)
	wtDir := filepath.Join(os.TempDir(), "chum-worktrees", taskID)

	// Create the worktree on a new branch
	if err := os.MkdirAll(filepath.Dir(wtDir), 0o755); err != nil {
		return "", fmt.Errorf("mkdir worktree parent: %w", err)
	}

	cmd := exec.CommandContext(ctx, "git", "worktree", "add", "-b", branch, wtDir, "HEAD")
	cmd.Dir = baseDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("git worktree add: %s: %w", string(out), err)
	}
	return wtDir, nil
}

// CleanupWorktree removes a git worktree.
func CleanupWorktree(ctx context.Context, baseDir, wtDir string) error {
	cmd := exec.CommandContext(ctx, "git", "worktree", "remove", "--force", wtDir)
	cmd.Dir = baseDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("git worktree remove: %s: %w", string(out), err)
	}
	return nil
}

// Push pushes the current branch to origin.
func Push(ctx context.Context, workDir string) error {
	cmd := exec.CommandContext(ctx, "git", "push", "-u", "origin", "HEAD")
	cmd.Dir = workDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("git push: %s: %w", string(out), err)
	}
	return nil
}

// CreatePR creates a pull request using gh CLI.
func CreatePR(ctx context.Context, workDir, title string) error {
	cmd := exec.CommandContext(ctx, "gh", "pr", "create",
		"--title", title,
		"--body", "Auto-generated by CHUM v2",
		"--fill-verbose",
	)
	cmd.Dir = workDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("gh pr create: %s: %w", string(out), err)
	}
	return nil
}

// CheckResult is the outcome of a single DoD check command.
type CheckResult struct {
	Command  string `json:"command"`
	Passed   bool   `json:"passed"`
	ExitCode int    `json:"exit_code"`
	Output   string `json:"output"`
}

// DoDResult is the aggregate outcome of all DoD checks.
type DoDResult struct {
	Passed   bool          `json:"passed"`
	Checks   []CheckResult `json:"checks"`
	Failures []string      `json:"failures"`
}

// RunDoDChecks executes each check command and returns the aggregate result.
func RunDoDChecks(ctx context.Context, workDir string, checks []string) DoDResult {
	result := DoDResult{Passed: true}
	for _, check := range checks {
		cr := runCheck(ctx, workDir, check)
		result.Checks = append(result.Checks, cr)
		if !cr.Passed {
			result.Passed = false
			result.Failures = append(result.Failures,
				fmt.Sprintf("%s (exit %d)", check, cr.ExitCode))
		}
	}
	return result
}

func runCheck(ctx context.Context, workDir, command string) CheckResult {
	parts := strings.Fields(command)
	if len(parts) == 0 {
		return CheckResult{Command: command, Passed: true}
	}
	cmd := exec.CommandContext(ctx, parts[0], parts[1:]...)
	cmd.Dir = workDir
	out, err := cmd.CombinedOutput()
	cr := CheckResult{
		Command: command,
		Output:  string(out),
	}
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			cr.ExitCode = exitErr.ExitCode()
		} else {
			cr.ExitCode = 1
		}
		cr.Passed = false
	} else {
		cr.Passed = true
	}
	return cr
}
